# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nAAp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nAAp
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'	

  target 'nAApTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nAApUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
